version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(asctime)s | %(levelname)s | %(name)s | %(threadName)s: %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: simple
        stream: ext://sys.stdout

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: simple
        filename: /var/log/apis/debug.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: simple
        filename: /var/log/apis/errors.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

loggers:
    apis-utils:
        level: DEBUG
        handlers: [console, info_file_handler, error_file_handler]
        propagate: no

root:
    level: DEBUG
    handlers: [console, info_file_handler, error_file_handler]